### ISSUE TITLE
Odd log messages when leaving Schedule Details Scene

### ISSUE THREAD

**Issue by Prismade** [Prismade/schedule-ios#35]
Something about TextureAtlasPage.
Happens only on iOS 13:
```
[VKDefault] TextureAtlasPage: Atlas page destroyed with outstanding references.:
Assertion with expression - _textureRefs == 0 : Failed in file -
/BuildRoot/Library/Caches/com.apple.xbs/Sources/VectorKit_Sim/
VectorKit-1606.32.10.8.3/src/TextureAtlas.cpp line - 604
```

**Comment by ChristianVarriale96** [comment]
I have the same problem in my app where from a table view go in a new view and after go back thanks to the navigation controller. help us

**Comment by eiselmayer** [comment]
I have the same problem in a different app and would be curious if you find a solution ;)

**Comment by Prismade** [comment]
I googled it a long time ago and it seemed like iOS problem, but I decided that I need more investigation.

**Comment by ChristianVarriale96** [comment]
For now i have this warning but the app works. I don’t know how to resolve



Inviato da myMail per iOS


venerdì 6 marzo 2020, 20:08 +0100 da notifications@github.com  <notifications@github.com>:

**Comment by ChristianVarriale96** [comment]
For now I don’t have solution. I have this warning but it works



Inviato da myMail per iOS


mercoledì 4 marzo 2020, 23:54 +0100 da notifications@github.com  <notifications@github.com>:

**Comment by sevriugin** [comment]
the same for me 
TextureAtlasPage: Atlas page destroyed with outstanding references.: Assertion with expression - _textureRefs == 0 : Failed in file - /BuildRoot/Library/Caches/com.apple.xbs/Sources/VectorKit_Sim/VectorKit-1606.32.10.8.3/src/TextureAtlas.cpp line - 604

**Comment by almazof** [comment]
I’ve gotten such a decision.

```
deinit {

            mapView.annotations.forEach{mapView.removeAnnotation($0)}

            mapView.delegate = nil

            print("deinit: MapViewController")
      }
```

**Comment by jkordyback** [comment]
This even happens with the Landmarks SwiftUI demo app from Apple. Hmmm.

**Comment by Prismade** [comment]
None of the offered solutions worked and there's the same log message in the official tutorial, thus it's likely an iOS bug
